src/Entity/Restaurant.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RestaurantTypeRepository")
 */
class Restaurant
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $hall_1;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $hall_2;

    /**
     * @ORM\Column(type="boolean", options={"default":0}, nullable=true)
     */
    private $active;

    /**
     * @var  \App\Entity\User
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="user_id")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $userId;

    /**
     * @var \App\Entity\Regions
     * @ORM\ManyToOne(targetEntity="App\Entity\Regions", inversedBy="region_id")
     * @ORM\JoinColumn(name="region_id", referencedColumnName="id")
     */
    private $region;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $comment;

    /**
     * @ORM\Column(type="date")
     */
    private $create_date;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $menu;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $cover_path;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $image_1;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $image_2;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $image_3;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $image_4;


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Bookings", mappedBy="restaurantId")
     * @ORM\JoinColumn(name="restaurantId", referencedColumnName="restaurantId")
     */
    private $restaurantId;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\UserNotifications", mappedBy="restaurantId")
     * @ORM\JoinColumn(name="notificationresId", referencedColumnName="restaurantId")
     */
    private $notificationresId;


    public function __construct()
    {
        $this->create_date = new \DateTime();
        $this->region = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * @param mixed $userId
     */
    public function setUserId($userId): void
    {
        $this->userId = $userId;
    }



    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getHall1()
    {
        return $this->hall_1;
    }

    /**
     * @param mixed $hall_1
     */
    public function setHall1($hall_1): void
    {
        $this->hall_1 = $hall_1;
    }

    /**
     * @return mixed
     */
    public function getHall2()
    {
        return $this->hall_2;
    }

    /**
     * @param mixed $hall_2
     */
    public function setHall2($hall_2): void
    {
        $this->hall_2 = $hall_2;
    }



    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * @param mixed $region
     */
    public function setRegion($region): void
    {
        $this->region = $region;
    }



    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getCreateDate(): ?\DateTimeInterface
    {
        return $this->create_date;
    }

    public function setCreateDate(\DateTimeInterface $create_date): self
    {
        $this->create_date = $create_date;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getMenu()
    {
        return $this->menu;
    }

    /**
     * @param mixed $menu
     */
    public function setMenu($menu): void
    {
        $this->menu = $menu;
    }

    /**
     * @return string
     */
    public function getCoverPath()
    {
        return $this->cover_path;
    }

    /**
     * @param string $cover_path
     */
    public function setCoverPath($cover_path)
    {

        if ($cover_path == null) {
            return false;
        } else {
            $this->cover_path = $cover_path;
        }
    }

    /**
     * @return string
     */
    public function getImage1()
    {
        return $this->image_1;
    }

    /**
     * @param string $image_1
     */
    public function setImage1($image_1)
    {
        if ($image_1 == null) {
            return false;
        } else {
            $this->image_1 = $image_1;
        }
    }

    /**
     * @return string
     */
    public function getImage2()
    {
        return $this->image_2;
    }

    /**
     * @param string $image_2
     */
    public function setImage2($image_2)
    {
        if ($image_2 == null) {
            return false;
        } else {
            $this->image_2 = $image_2;
        }
    }

    /**
     * @return string
     */
    public function getImage3()
    {
        return $this->image_3;
    }

    /**
     * @param string $image_3
     */
    public function setImage3($image_3)
    {
        if ($image_3 == null) {
            return false;
        } else {
            $this->image_3 = $image_3;
        }
    }

    /**
     * @return string
     */
    public function getImage4()
    {
        return $this->image_4;
    }

    /**
     * @param string $image_4
     */
    public function setImage4($image_4)
    {
        if ($image_4 == null) {
            return false;
        } else {
            $this->image_4 = $image_4;
        }
    }



    public function __toString()
    {
        return (string) $this->region;
        return (string) $this->cover_path;
        return (string) $this->image_1;
        return (string) $this->image_2;
        return (string) $this->image_3;
        return (string) $this->image_4;
    }
}

src/Controller/Restaurants.php
<?php
/**
 * Created by PhpStorm.
 * User: blerimi_v
 * Date: 1/14/2019
 * Time: 11:15 PM
 */

namespace App\Controller;


use App\Entity\Regions;
use App\Entity\Restaurant;
use App\Entity\User;
use App\Entity\UserNotifications;
use App\Form\GuestBookingType;
use App\Form\RestaurantType;
use phpDocumentor\Reflection\Types\This;
use App\Form\UserType;
use App\Repository\RestaurantTypeRepository;
use App\Repository\UserRepository;
use Knp\Component\Pager\Pagination\PaginationInterface;
use Knp\Component\Pager\PaginatorInterface;
use function MongoDB\BSON\toJSON;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class Restaurants
 * @package App\Controller
 * @Route("/restaurants")
 */
class Restaurants extends Controller
{
    /**
     * @Route("/", name="restaurants")
     */
    public function index(Request $request, PaginatorInterface $paginator)
    {
        $repository = $this->getDoctrine()->getManager();
        $restaurants =$repository->getRepository('App:Bookings')->findByBooking(
            $request->query->get('search')['region'],
            $request->query->get('search')['name'],
            $request->query->get('search')['from_date'],
            $request->query->get('search')['to_date'],
            $request
        );

        $pagination = $paginator->paginate(
            $restaurants,
            $request->query->getInt('page', 1),
            20
        );


        return $this->render('restaurants/index.html.twig', [
            'restaurants' => $pagination,
        ]);
    }

    /**
     * @Route("/new", name="new_restaurant")
     */
    public function newAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $restaurant = new Restaurant();
        $lastId = $em->getRepository('App:Restaurant')->lastRestarantId();
        if ($lastId != null) {
            $currentId = $lastId->getId() + 1 ;
        }

        $form = $this->createForm(RestaurantType::class, $restaurant);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
             $fileCover = $restaurant->getCoverPath();
             $image1 = $restaurant->getImage1();
             $image2 = $restaurant->getImage2();
             $image3 = $restaurant->getImage3();
             $image4 = $restaurant->getImage4();


             if ($fileCover != null) {
                 $fileNameCover = $this->generateUniqueFileName().'.'.$fileCover->guessExtension();
                 $fileCover->move($this->getParameter('uploads_directory').'/'.$currentId,$fileNameCover);
                 $restaurant->setCoverPath($fileNameCover);

             }
             if ($image1 != null) {
                 $fileNameImage1 = $this->generateUniqueFileName().'.'.$image1->guessExtension();
                 $image1->move($this->getParameter('uploads_directory').'/'.$currentId,$fileNameImage1);
                 $restaurant->setImage1($fileNameImage1);

             }
             if ($image2 != null) {
                 $fileNameImage2 = $this->generateUniqueFileName().'.'.$image2->guessExtension();
                 $image2->move($this->getParameter('uploads_directory').'/'.$currentId,$fileNameImage2);
                 $restaurant->setImage2($fileNameImage2);
             }
             if ($image3 != null) {
                 $fileNameImage3 = $this->generateUniqueFileName().'.'.$image3->guessExtension();
                 $image3->move($this->getParameter('uploads_directory').'/'.$currentId,$fileNameImage3);
                 $restaurant->setImage3($fileNameImage3);
             }
             if ($image4 != null) {
                 $fileNameImage4 = $this->generateUniqueFileName().'.'.$image4->guessExtension();
                 $image4->move($this->getParameter('uploads_directory').'/'.$currentId,$fileNameImage4);
                 $restaurant->setImage4($fileNameImage4);

             }

            $em->persist($restaurant);
            $em->flush();
            $this->addFlash('success', 'Your changes were saved!');
            return $this->redirectToRoute('restaurants');
        }
        return $this->render('restaurants/new.html.twig', [
            'form' => $form->createView(),
            'request' => $request->query->get('search')

        ]);
    }

    /**
     * @Route("/edit/{id}", name="edit_restaurant")
     */
    public function editAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();
        $restaurant = $em->getRepository('App:Restaurant')->find($id);
        $form = $this->createForm(RestaurantType::class, $restaurant);
        $form->handleRequest($request);


        if (!$restaurant) {
            $this->addFlash('danger', 'Your Restaurant not exist');
            return $this->redirectToRoute('restaurants');
        }
        $fileCover = $restaurant->getCoverPath();
        $image1 = $restaurant->getImage1();
        $image2 = $restaurant->getImage2();
        $image3 = $restaurant->getImage3();
        $image4 = $restaurant->getImage4();


        if ($form->isSubmitted() && $form->isValid()) {
            if ($request->files->get('restaurant')['coverPath'] != null) {
                $fileNameCover = $this->generateUniqueFileName().'.'.$fileCover->guessExtension();
                $fileCover->move($this->getParameter('uploads_directory').'/'.$id,$fileNameCover);
                $restaurant->setCoverPath($fileNameCover);
            }
            if ($request->files->get('restaurant')['image1'] != null) {
                $fileNameImage1 = $this->generateUniqueFileName().'.'.$image1->guessExtension();
                $image1->move($this->getParameter('uploads_directory').'/'.$id,$fileNameImage1);
                $restaurant->setImage1($fileNameImage1);

            }
            if ($request->files->get('restaurant')['image2'] != null) {
                $fileNameImage2 = $this->generateUniqueFileName().'.'.$image2->guessExtension();
                $image2->move($this->getParameter('uploads_directory').'/'.$id,$fileNameImage2);
                $restaurant->setImage2($fileNameImage2);
            }
            if ($request->files->get('restaurant')['image3'] != null) {
                $fileNameImage3 = $this->generateUniqueFileName().'.'.$image3->guessExtension();
                $image3->move($this->getParameter('uploads_directory').'/'.$id,$fileNameImage3);
                $restaurant->setImage3($fileNameImage3);
            }

            if ($request->files->get('restaurant')['image4'] != null) {
                $fileNameImage4 = $this->generateUniqueFileName().'.'.$image4->guessExtension();
                $image4->move($this->getParameter('uploads_directory').'/'.$id,$fileNameImage4);
                $restaurant->setImage4($fileNameImage4);

            }

            $em->flush();
            $this->addFlash('success', 'Your Restaurant has been edited');
            return $this->redirectToRoute('restaurants');
        }
        return $this->render('restaurants/edit.html.twig', [
            'form' => $form->createView()

        ]);

    }

    /**
     * @Route("/view/{id}", name="view_restaurant")
     */
    public function viewAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();
        $restaurant = $em->getRepository('App:Restaurant')->find($id);
        $booking = $em->getRepository('App:Bookings')->findBy([
           'restaurantId' => $id
        ]);


        return $this->render('restaurants/view.html.twig', [
                'restaurant' => $restaurant,
                'booking' => $booking,
                'project_path' => $this->getParameter('project_path'),

            ]
        );
    }

    /**
     * @Route("/remove/{id}", name="remove_restaurant")
     */
    public function removeAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        $restaurant = $em->getRepository('App:Restaurant')->find($id);
        if (!$restaurant) {
            $this->addFlash('danger', 'Your Restaurant does not exist');
            return $this->redirectToRoute('restaurants');
        }
        $em->remove($restaurant);
        $em->flush();

        $this->addFlash('success', 'Your Restaurant has been deleted');
        return $this->redirectToRoute('restaurants');
    }


    /**
     * @Route("/user/myRestaurants", name="my_restaurants")
     */
    public function myRestaurantsAction(Request $request)
    {
        $user = $this->getUser();
        if (!$user) {
            $this->addFlash('danger', 'Please login');
            return $this->redirectToRoute('restaurants');
        }

        $em = $this->getDoctrine()->getManager();
        $myRestaurant = $em->getRepository('App:Restaurant')->myRestaturant($user->getId());

        return $this->render('user/myRestaurants.html.twig', [
                'restaurant' => $myRestaurant,

            ]
        );

    }

    /**
     * @Route("/user/myRestaurant/{id}", name="my_restaurant")
     */
    public function myRestaurantAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();
        $myRestaurant = $em->getRepository('App:Restaurant')->findBy([
            'id' => $id,
            'userId' => $this->getUser()
        ]);

        return $this->render('user/myView.html.twig', [
            'restaurant' => $myRestaurant,
        ]);
    }

    private function generateUniqueFileName()
    {
        return md5(uniqid());
    }

}

templates/restaurants/edit.html.twig
{% extends 'base.html.twig' %}
{% block title %} Edit Restaurant {% endblock %}
{% block body %}
    <div class="wrapper">
        <div class="main-panel">
            {{ include('navigation.html.twig') }}
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title">Edit Profile</h4>
                        <p class="card-category">Complete your profile</p>
                    </div>
                    {{ form_start(form) }}
                    <div class="row">
                        <div class="col-md-8">
                            <div class="card-body">
                                {{ form_row(form.name) }}
                                {{ form_row(form.userId) }}
                                {{ form_row(form.hall1) }}
                                {{ form_row(form.hall2) }}
                                {{ form_row(form.region) }}
                                {{ form_row(form.comment) }}
                                {{ form_row(form.active, {label_attr: {class: 'checkbox-custom'} }) }}
                            </div>
                            <div class="row card-body">
                                <div class="col-lg-3 col-md-4 col-xs-6 thumb">

                                    {% if form.coverPath.vars.data is not null %}
                                        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal"
                                           data-title="Cover Image"
                                           data-image="{{ asset('uploads/' ~ form.vars.data.id ~'/' ~ form.coverPath.vars.data) }}"
                                           data-target="#image-gallery">
                                            <img class="img-thumbnail"
                                                 src="{{ asset('uploads/' ~ form.vars.data.id ~'/' ~ form.coverPath.vars.data) }}"
                                                 alt="Another alt text">
                                        </a>
                                    {% endif %}
                                    Cover Image
                                    {{ form_widget(form.coverPath) }}
                                </div>
                                <div class="col-lg-2 col-md-4 col-xs-6 thumb">
                                    {% if form.image1.vars.data is not null %}
                                        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal"
                                           data-title="Image 1"
                                           data-image="{{ asset('uploads/' ~ form.vars.data.id ~'/' ~ form.image1.vars.data) }}"
                                           data-target="#image-gallery">
                                            <img class="img-thumbnail"
                                                 src="{{ asset('uploads/' ~ form.vars.data.id ~'/' ~ form.image1.vars.data) }}"
                                                 alt="Another alt text">
                                        </a>
                                    {% endif %}
                                    Image 1
                                    {{ form_widget(form.image1) }}
                                </div>
                                <div class="col-lg-2 col-md-4 col-xs-6 thumb">
                                    {% if form.image2.vars.data is not null %}
                                        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal"
                                           data-title="Image 2"
                                           data-image="{{ asset('uploads/' ~ form.vars.data.id ~'/' ~ form.image2.vars.data) }}"
                                           data-target="#image-gallery">
                                            <img class="img-thumbnail"
                                                 src="{{ asset('uploads/' ~ form.vars.data.id ~'/' ~ form.image2.vars.data) }}"
                                                 alt="Another alt text">
                                        </a>
                                    {% endif %}
                                    Image 2
                                    {{ form_widget(form.image2) }}
                                </div>
                                <div class="col-lg-2 col-md-4 col-xs-6 thumb">
                                    {% if form.image3.vars.data is not null %}
                                        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal"
                                           data-title="Image 3"
                                           data-image="{{ asset('uploads/' ~ form.vars.data.id ~'/' ~ form.image3.vars.data) }}"
                                           data-target="#image-gallery">
                                            <img class="img-thumbnail"
                                                 src="{{ asset('uploads/' ~ form.vars.data.id ~'/' ~ form.image3.vars.data) }}"
                                                 alt="Another alt text">
                                        </a>
                                    {% endif %}
                                    Image 3
                                    {{ form_widget(form.image3) }}
                                </div>
                                <div class="col-lg-2 col-md-4 col-xs-6 thumb">
                                    {% if form.image4.vars.data is not null %}
                                        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal"
                                           data-title="Image 4"
                                           data-image="{{ asset('uploads/' ~ form.vars.data.id ~'/' ~ form.image4.vars.data) }}"
                                           data-target="#image-gallery">
                                            <img class="img-thumbnail"
                                                 src="{{ asset('uploads/' ~ form.vars.data.id ~'/' ~ form.image4.vars.data) }}"
                                                 alt="Another alt text">
                                        </a>
                                    {% endif %}
                                    Image 4
                                    {{ form_widget(form.image4) }}
                                </div>
                                {{ include('modal/galery.html.twig') }}
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card-body">
                                {{ form_row(form.menu) }}
                            </div>
                        </div>
                    </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/restaurants/index.html.twig
{% extends 'base.html.twig' %}
{% block title %} Restaurants {% endblock %}
{% block search %}{% endblock %}
{% block body %}
    <div class="">
        <div class="main-panel">
            {% include 'navigation.html.twig' %}
            <div class="col-md-12">
                {{ render(controller('App\\Controller\\SearchController::searchAction')) }}
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title ">Restaurants Table</h4>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-primary">
                                <tr>
                                    {% if app.user is not null %}
                                        <th>
                                            Username
                                        </th>
                                    {% endif %}
                                    <th{% if restaurants.isSorted('restaurantId.name') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(restaurants, 'Name', 'restaurantId.name') }}</th>
                                    <th>
                                        Hall_1
                                    </th>
                                    <th>
                                        Hall_2
                                    </th>
                                    {% if is_granted('ROLE_SUPER_ADMIN') %}
                                        <th>
                                            Acive
                                        </th>
                                    {% endif %}
                                    <th>
                                        Regions
                                    </th>
                                    <th{% if restaurants.isSorted('restaurantId.comment') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(restaurants, 'Comment', 'restaurantId.comment') }}</th>

                                    <th style="width: 27%">
                                        Action
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for restaurant in restaurants %}
                                    <tr>
                                        {% if app.user is not null %}
                                            <td>
                                                {{ restaurant.restaurantId.getUserId.username }}
                                            </td>
                                        {% endif %}
                                        <td>
                                            {{ restaurant.restaurantId.name }}
                                        </td>
                                        <td>
                                            {{ restaurant.restaurantId.hall1 }}
                                        </td>
                                        <td>
                                            {{ restaurant.restaurantId.hall2 }}
                                        </td>
                                        {% if is_granted('ROLE_SUPER_ADMIN') %}
                                            <td>
                                                {{ restaurant.restaurantId.active }}
                                            </td>
                                        {% endif %}
                                        <td>
                                            {{ restaurant.restaurantId.region.name }}
                                        </td>
                                        <td>
                                            {{ restaurant.restaurantId.comment }}
                                        </td>
                                        <td>
                                            {% if is_granted(['ROLE_SUPER_ADMIN']) %}
                                                <a href="{{ path('view_restaurant',{'id':restaurant.restaurantId.id}) }}"
                                                   class="btn btn-sm btn-primary">View</a>
                                                <a href="{{ path('edit_restaurant',{'id':restaurant.restaurantId.id}) }} "
                                                   class="btn btn-warning btn-sm">Edit</a>
                                                <a href="#" data-toggle="modal"
                                                   data-target="#exampleModal"
                                                   class="btn btn-danger btn-sm">Remove </a>
                                                {% if restaurant.reserved %}
                                                    <i class="material-icons text-danger">lens</i>
                                                {% else %}
                                                    <i class="material-icons text-success">lens</i>
                                                {% endif %}
                                                {{ include('modal/modal.html.twig') }}
                                            {% else %}
                                                <a href="{{ path('view_restaurant',{'id':restaurant.restaurantId.id}) }}"
                                                   class="btn btn-sm btn-info">View</a>
                                                {% if restaurant.status %}
                                                    <a href="#" class="btn btn-danger btn-sm disabled" role="button" aria-disabled="true">Reserved</a>
                                                {% else %}
                                                    <a href="#" class="btn btn-success btn-sm" data-toggle="modal" data-target="#guestBook{{ restaurant.restaurantId.id }}" role="button">Book Now</a>
                                                    {{ include('modal/guest_book.html.twig') }}
                                                {% endif %}
                                                {% if restaurant.period == 1 %}NIGHT
                                                {% elseif restaurant.period == 0 %}DAY
                                                    {% elseif restaurant.period == 3  %}
                                                    ALLDAY
                                                {% endif %}
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            {{ knp_pagination_render(restaurants) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}